version: "3"
services:
  backend:
    build:
      context: ./backend/django_challenge
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
