# Generated by Django 4.2.5 on 2023-10-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='image_url',
        ),
        migrations.AddField(
            model_name='painting',
            name='image_filename',
            field=models.CharField(default='/static/gallery/25.jpg', max_length=100),
        ),
    ]
